version: "3"
networks:
  hyperledger:
    external:
      name: hyperledger
services:
  zookeeper1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.hostname == peer1]
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper:0.4.10
    networks:
      hyperledger:
        aliases:
        - zookeeper1.example.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.hostname == peer1]
    hostname: zookeeper2
    image: hyperledger/fabric-zookeeper:0.4.10
    networks:
      hyperledger:
        aliases:
        - zookeeper2.example.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger
    - ZOO_MY_ID=2
    - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.hostname == peer1]
    hostname: zookeeper3
    image: hyperledger/fabric-zookeeper:0.4.10
    networks:
      hyperledger:
        aliases:
        - zookeeper3.example.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger
    - ZOO_MY_ID=3
    - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
